name: event_finder
description: A new Flutter project for Event Finder
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.4.0
  shared_preferences: ^2.0.13
  google_maps_flutter: ^2.6.0
  geolocator: ^9.0.2
  # yandex_mapkit: ^4.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/marker.png
